name: ecoleami1_0
description: EcoleAmi 1.0

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.4
    #  firebase_auth: ^0.8.0+3
  shared_preferences: ^0.5.6+3
  flutter_launcher_icons: ^0.7.4
  cloud_firestore: ^0.13.0+1
  websocket: ^0.0.5
  connectivity: ^0.4.8+2
  carousel_slider: ^1.4.1
  rxdart: ^0.18.0
  bubble: ^1.1.9+1
  shimmer: ^1.1.0
  cached_network_image: ^2.0.0
  carousel_pro: ^1.0.0
  flutter_screenutil: ^1.0.2
  progress_dialog: ^1.2.1
  web_socket_channel: ^1.1.0
  fluttertoast: ^3.1.3
  datetime_picker_formfield: ^0.1.8
  image_picker: ^0.6.0+17
  firebase_storage: ^3.0.3
  url_launcher: ^5.4.0
  firebase_messaging: ^6.0.13
  overlay_support: ^1.0.0
  firebase_in_app_messaging: ^0.1.1+3
  firebase_analytics: ^5.0.11
  barcode_scan: ^3.0.1
  qr_flutter: ^3.0.1
  file_picker: ^1.9.0+1
  open_file: ^3.0.1
  contactus: ^1.1.4
  local_auth: ^0.4.0+1
  pie_chart: ^3.1.1
  email_validator: ^1.0.4
  path_provider: ^1.6.0
  flutter_downloader: ^1.4.4




dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/ecoleami.png
    - images/dummyimg.png
    - images/loading.gif
    - images/logo.jpeg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
